// AI 员工模板 seed（30 个，覆盖 15 行业 × 2 角色）
export const agentTemplates = [
  {
    name: '跨境文案专员',
    role: 'copywriter',
    description: '专为跨境电商生成多平台商品文案',
    category: 'ecommerce',
    skills: ['content:product_title', 'content:listing', 'content:faq'],
    tools: [],
    priceSuggestion: 9.99,
  },
  {
    name: 'TikTok 内容官',
    role: 'content_creator',
    description: '生成 TikTok 爆款脚本与文案',
    category: 'social',
    skills: ['content:tiktok_script', 'content:instagram'],
    tools: [],
    priceSuggestion: 9.99,
  },
  {
    name: '知识库客服',
    role: 'customer_service',
    description: '基于知识库的 RAG 智能客服',
    category: 'support',
    skills: ['rag:qa'],
    tools: ['query_kb'],
    priceSuggestion: 14.99,
  },
  {
    name: 'SEO 文案师',
    role: 'seo_writer',
    description: '生成 SEO 优化博客与商品页',
    category: 'content',
    skills: ['content:seo_blog', 'content:landing_page'],
    tools: [],
    priceSuggestion: 9.99,
  },
  {
    name: '广告优化师',
    role: 'ad_specialist',
    description: '生成 Facebook/Google 广告文案',
    category: 'ad',
    skills: ['content:facebook_ad', 'content:google_ads'],
    tools: [],
    priceSuggestion: 12.99,
  },
  {
    name: '邮件营销员',
    role: 'email_marketer',
    description: '生成邮件营销内容与序列',
    category: 'email',
    skills: ['content:email_marketing'],
    tools: ['send_email'],
    priceSuggestion: 9.99,
  },
  {
    name: '销售跟进员',
    role: 'sales',
    description: 'AI 销售跟进与线索管理',
    category: 'crm',
    skills: ['crm:sales_followup', 'crm:customer_profile'],
    tools: ['query_kb'],
    priceSuggestion: 19.99,
  },
  {
    name: '多语言翻译官',
    role: 'translator',
    description: '高质量多语言翻译与本地化',
    category: 'translation',
    skills: ['content:multilingual'],
    tools: [],
    priceSuggestion: 7.99,
  },
  {
    name: '品牌语气守护者',
    role: 'brand_guardian',
    description: '确保所有内容符合品牌语气',
    category: 'brand',
    skills: ['content:brand_voice'],
    tools: [],
    priceSuggestion: 12.99,
  },
  {
    name: '差评处理专家',
    role: 'review_handler',
    description: '专业回复差评，维护品牌声誉',
    category: 'support',
    skills: ['content:negative_review'],
    tools: [],
    priceSuggestion: 7.99,
  },
  {
    name: '餐饮运营助手',
    role: 'operations',
    description: '餐饮行业 AI 运营：菜单描述、外卖文案、评价回复',
    category: 'restaurant',
    skills: ['content:product_title', 'content:faq'],
    tools: [],
    priceSuggestion: 14.99,
  },
  {
    name: '教育培训顾问',
    role: 'education',
    description: '课程文案、答疑、学员跟进',
    category: 'education',
    skills: ['rag:qa', 'content:email_marketing'],
    tools: ['query_kb'],
    priceSuggestion: 14.99,
  },
  {
    name: '房产销售助手',
    role: 'real_estate',
    description: '房源描述、客户跟进、市场分析',
    category: 'real_estate',
    skills: ['content:product_title', 'crm:sales_followup'],
    tools: [],
    priceSuggestion: 19.99,
  },
  {
    name: '健身教练 AI',
    role: 'fitness',
    description: '训练计划文案、会员跟进、社媒内容',
    category: 'fitness',
    skills: ['content:product_title', 'content:instagram'],
    tools: [],
    priceSuggestion: 9.99,
  },
  {
    name: '美容顾问 AI',
    role: 'beauty',
    description: '产品推荐文案、护肤知识问答、社媒种草',
    category: 'beauty',
    skills: ['rag:qa', 'content:instagram', 'content:tiktok_script'],
    tools: ['query_kb'],
    priceSuggestion: 12.99,
  },
  {
    name: 'SaaS 增长助手',
    role: 'growth',
    description: '落地页文案、邮件序列、用户激活',
    category: 'saas',
    skills: ['content:landing_page', 'content:email_marketing', 'content:seo_blog'],
    tools: [],
    priceSuggestion: 19.99,
  },
  {
    name: '招聘助手',
    role: 'recruiter',
    description: 'JD 生成、候选人筛选、面试安排',
    category: 'hr',
    skills: ['content:product_title', 'content:email_marketing'],
    tools: [],
    priceSuggestion: 14.99,
  },
  {
    name: '财税顾问 AI',
    role: 'finance',
    description: '财税知识问答、客户咨询、报告摘要',
    category: 'finance',
    skills: ['rag:qa', 'content:email_marketing'],
    tools: ['query_kb'],
    priceSuggestion: 24.99,
  },
  {
    name: '旅游规划师',
    role: 'travel',
    description: '行程文案、酒店描述、客户咨询',
    category: 'travel',
    skills: ['content:product_title', 'rag:qa', 'content:email_marketing'],
    tools: ['query_kb'],
    priceSuggestion: 12.99,
  },
  {
    name: '宠物顾问 AI',
    role: 'pet',
    description: '宠物知识问答、产品推荐、社媒内容',
    category: 'pet',
    skills: ['rag:qa', 'content:instagram'],
    tools: ['query_kb'],
    priceSuggestion: 7.99,
  },
  {
    name: '自媒体运营官',
    role: 'media',
    description: '多平台内容生成与排期',
    category: 'media',
    skills: ['content:tiktok_script', 'content:instagram', 'content:seo_blog'],
    tools: [],
    priceSuggestion: 14.99,
  },
  {
    name: '律所助理 AI',
    role: 'legal',
    description: '法律文书摘要、客户咨询初筛',
    category: 'legal',
    skills: ['rag:qa', 'content:email_marketing'],
    tools: ['query_kb'],
    priceSuggestion: 29.99,
  },
  {
    name: '咨询顾问 AI',
    role: 'consultant',
    description: '行业报告摘要、客户提案、知识问答',
    category: 'consulting',
    skills: ['rag:qa', 'content:landing_page', 'content:email_marketing'],
    tools: ['query_kb'],
    priceSuggestion: 24.99,
  },
  {
    name: '电商数据分析师',
    role: 'analyst',
    description: '运营数据洞察、日报生成、趋势分析',
    category: 'analytics',
    skills: ['analytics:data_analysis', 'analytics:daily_brief'],
    tools: [],
    priceSuggestion: 19.99,
  },
  {
    name: '落地页设计师',
    role: 'designer',
    description: '高转化落地页文案与结构生成',
    category: 'content',
    skills: ['content:landing_page'],
    tools: [],
    priceSuggestion: 12.99,
  },
  {
    name: '社群运营官',
    role: 'community',
    description: '社群内容、活动文案、成员互动',
    category: 'community',
    skills: ['content:email_marketing', 'content:instagram'],
    tools: [],
    priceSuggestion: 9.99,
  },
  {
    name: '保险顾问 AI',
    role: 'insurance',
    description: '保险产品说明、客户问答、方案对比',
    category: 'insurance',
    skills: ['rag:qa', 'content:email_marketing'],
    tools: ['query_kb'],
    priceSuggestion: 19.99,
  },
  {
    name: '物流客服 AI',
    role: 'logistics',
    description: '物流查询、异常处理、客户通知',
    category: 'logistics',
    skills: ['rag:qa', 'content:email_marketing'],
    tools: ['query_kb'],
    priceSuggestion: 12.99,
  },
  {
    name: '批发业务员 AI',
    role: 'wholesale',
    description: '报价单生成、客户跟进、订单确认',
    category: 'wholesale',
    skills: ['content:email_marketing', 'crm:sales_followup'],
    tools: [],
    priceSuggestion: 14.99,
  },
  {
    name: '全栈运营 AI',
    role: 'all_rounder',
    description: '内容+客服+销售+分析，一人顶一队',
    category: 'general',
    skills: ['content:product_title', 'rag:qa', 'crm:sales_followup', 'analytics:daily_brief'],
    tools: ['query_kb'],
    priceSuggestion: 29.99,
  },
];
